module.exports = {
  name: "Framework",
  description: "Framework for setting up projects with Javascript",
  version: "1.0.0",
  author: "Martin Spierings",
  repository: 'git',
  private: true,
  dependencies: {
    'body-parser': '1.8.2',
    bower: '1.3.11',
    express: '4.9.1',
    grunt: '0.4.5',
    'grunt-express-server': '0.4.19',
    'grunt-open': '0.2.3',
    'grunt-parallel': '0.3.1',
    jade: '1.7.0',
    'load-grunt-tasks': '0.6.0',
    'socket.io': '1.1.0',
    'time-grunt': '1.0.0'
  },
  devDependencies: {
    'body-parser': '1.8.2',
    bower: '1.3.11',
    connect: '3.2.0',
    express: '4.9.1',
    grunt: '0.4.5',
    'grunt-concurrent': '1.0.0',
    'grunt-contrib-clean': '0.6.0',
    'grunt-contrib-compass': '1.0.1',
    'grunt-contrib-connect': '0.8.0',
    'grunt-contrib-copy': '0.5.0',
    'grunt-contrib-jshint': '0.10.0',
    'grunt-contrib-sass': '0.8.1',
    'grunt-contrib-uglify': '0.5.1',
    'grunt-contrib-watch': '0.6.1',
    'grunt-express-server': '0.4.19',
    'grunt-jsbeautifier': '0.2.7',
    'grunt-open': '0.2.3',
    'grunt-parallel': '0.3.1',
    jade: '1.7.0',
    'load-grunt-configs': '^0.4.0',
    'load-grunt-tasks': '0.6.0',
    'socket.io': '1.1.0',
    supervisor: '0.6.0',
    'time-grunt': '1.0.0'
  }
};
